
export const TODO_REQUEST = "TODO_REQUEST"
export const TODO_SUCCESS = "TODO_SUCCESS"
export const TODO_FAILURE = "TODO_FAILURE"

export const TODO_POST_REQUEST = "TODO_POST_REQUEST"
export const TODO_POST_SUCCESS = "TODO_POST_SUCCESS"
export const TODO_POST_FAILED = "TODO_POST_FAILED"


export const TODO_UPDATE_REQUEST = "TODO_UPDATE_REQUEST"
export const TODO_UPDATE_SUCCESS = "TODO_UPDATE_SUCCESS"
export const TODO_UPDATE_FAILED = "TODO_UPDATE_FAILED"

export const TODO_DELETE_REQUEST = "TODO_DELETE_REQUEST"
export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS"
export const TODO_DELETE_FAILED = "TODO_DELETE_FAILED" 